from typing import Optional

import torch
from torch import profiler

from ..lib import generate_kvectors_for_ewald
from ..potentials import PotentialDipole


class CalculatorDipole(torch.nn.Module):
    """TODO: Add docstring"""

    def __init__(
        self,
        potential: PotentialDipole,
        full_neighbor_list: bool = False,
        prefactor: float = 1.0,
        lr_wavelength: Optional[float] = None,
        dtype: Optional[torch.dtype] = None,
        device: Optional[torch.device] = None,
    ):
        super().__init__()

        assert isinstance(potential, PotentialDipole), (
            f"Potential must be an instance of Potential, got {type(potential)}"
        )
        self.potential = potential
        self.lr_wavelength = lr_wavelength

        assert (
            self.lr_wavelength is not None
            and self.potential.smearing is not None
            or (self.lr_wavelength is None and self.potential.smearing is None)
        ), "Either both `lr_wavelength` and `smearing` must be set or both must be None"
        self.device = "cpu" if device is None else device
        self.dtype = torch.get_default_dtype() if dtype is None else dtype

        assert self.dtype == self.potential.dtype, (
            f"Potential and Calculator must have the same dtype, got {self.dtype} and "
            f"{self.potential.dtype}"
        )
        assert self.device == self.potential.device, (
            f"Potential and Calculator must have the same device, got {self.device} and "
            f"{self.potential.device}"
        )

        self.full_neighbor_list = full_neighbor_list

        self.prefactor = prefactor

    def _compute_rspace(
        self,
        dipoles: torch.Tensor,
        neighbor_indices: torch.Tensor,
        neighbor_vectors: torch.Tensor,
    ) -> torch.Tensor:
        """TODO: Add docstring"""
        # Compute the pair potential terms V(r_ij) for each pair of atoms (i,j)
        # contained in the neighbor list
        with profiler.record_function("compute bare potential"):
            if self.potential.smearing is None:
                potentials_bare = self.potential.from_dist(neighbor_vectors)
            else:
                potentials_bare = self.potential.sr_from_dist(neighbor_vectors)

        # Multiply the bare potential terms V(r_ij) with the corresponding dipoles
        # of ``atom j'' to obtain q_j*V(r_ij). Since each atom j can be a neighbor of
        # multiple atom i's, we need to access those from neighbor_indices
        atom_is = neighbor_indices[:, 0]
        atom_js = neighbor_indices[:, 1]
        with profiler.record_function("compute real potential"):
            contributions_is = torch.einsum(
                "ij,ijk->ik", dipoles[atom_js], potentials_bare
            )

        # For each atom i, add up all contributions of the form q_j*V(r_ij) for j
        # ranging over all of its neighbors.
        with profiler.record_function("assign potential"):
            potential = torch.zeros_like(dipoles)
            potential.index_add_(0, atom_is, contributions_is)
            # If we are using a half neighbor list, we need to add the contributions
            # from the "inverse" pairs (j, i) to the atoms i
            if not self.full_neighbor_list:
                contributions_js = torch.einsum(
                    "ij,ijk->ik", dipoles[atom_is], potentials_bare
                )
                potential.index_add_(0, atom_js, contributions_js)

        # Compensate for double counting of pairs (i,j) and (j,i)
        return potential / 2

    def _compute_kspace(
        self,
        dipoles: torch.Tensor,
        cell: torch.Tensor,
        positions: torch.Tensor,
    ) -> torch.Tensor:
        # Define k-space cutoff from required real-space resolution
        k_cutoff = 2 * torch.pi / self.lr_wavelength

        # Compute number of times each basis vector of the reciprocal space can be
        # scaled until the cutoff is reached
        basis_norms = torch.linalg.norm(cell, dim=1)
        ns_float = k_cutoff * basis_norms / 2 / torch.pi
        ns = torch.ceil(ns_float).long()

        # Generate k-vectors and evaluate
        kvectors = generate_kvectors_for_ewald(ns=ns, cell=cell)
        knorm_sq = torch.sum(kvectors**2, dim=1)
        # G(k) is the Fourier transform of the Coulomb potential
        # generated by a Gaussian charge density
        # We remove the singularity at k=0 by explicitly setting its
        # value to be equal to zero. This mathematically corresponds
        # to the requirement that the net charge of the cell is zero.
        # G = 4 * torch.pi * torch.exp(-0.5 * smearing**2 * knorm_sq) / knorm_sq
        G = self.potential.lr_from_k_sq(knorm_sq)

        # Compute the energy using the explicit method that
        # follows directly from the Poisson summation formula.
        # For this, we precompute trigonometric factors for optimization, which leads
        # to N^2 rather than N^3 scaling.
        trig_args = kvectors @ (positions.T)  # [k, i]
        mu_k_product = dipoles @ kvectors.T  # [i, k]
        c = torch.cos(trig_args)  # [k, i]
        s = torch.sin(trig_args)  # [k, i]
        sc = torch.stack([c, s], dim=0)  # [2 "f", k, i]
        sc_summed_G = torch.einsum("fki, ik, ic, k->fkc", sc, mu_k_product, dipoles, G)
        energy = torch.einsum("fkc, ik ,fki->ic", sc_summed_G, mu_k_product, sc)
        energy /= torch.abs(cell.det())

        # Remove the self-contribution: Using the Coulomb potential as an
        # example, this is the potential generated at the origin by the fictituous
        # Gaussian charge density in order to split the potential into a SR and LR part.
        # This contribution always should be subtracted since it depends on the smearing
        # parameter, which is purely a convergence parameter.
        energy -= dipoles * self.potential.self_contribution()

        # Step 5: The method requires that the unit cell is charge-neutral.
        # If the cell has a net charge (i.e. if sum(charges) != 0), the method
        # implicitly assumes that a homogeneous background charge of the opposite sign
        # is present to make the cell neutral. In this case, the potential has to be
        # adjusted to compensate for this.
        # An extra factor of 2 is added to compensate for the division by 2 later on
        # ivolume = torch.abs(cell.det()).pow(-1)
        # charge_tot = torch.sum(charges, dim=0)
        # prefac = self.potential.background_correction()
        # energy -= 2 * prefac * charge_tot * ivolume
        # Compensate for double counting of pairs (i,j) and (j,i)
        return energy / 2

    def forward(
        self,
        dipoles: torch.Tensor,
        cell: torch.Tensor,
        positions: torch.Tensor,
        neighbor_indices: torch.Tensor,
        neighbor_vectors: torch.Tensor,
    ):
        r"""TODO: Add docstring"""
        # self._validate_compute_parameters(
        #     charges=charges,
        #     cell=cell,
        #     positions=positions,
        #     neighbor_indices=neighbor_indices,
        #     neighbor_distances=neighbor_distances,
        #     smearing=self.potential.smearing,
        # )

        # Compute short-range (SR) part using a real space sum
        potential_sr = self._compute_rspace(
            dipoles=dipoles,
            neighbor_indices=neighbor_indices,
            neighbor_vectors=neighbor_vectors,
        )

        if self.potential.smearing is None:
            return self.prefactor * potential_sr
        # Compute long-range (LR) part using a Fourier / reciprocal space sum
        potential_lr = self._compute_kspace(
            dipoles=dipoles,
            cell=cell,
            positions=positions,
        )

        return self.prefactor * (potential_sr + potential_lr)

    # @staticmethod
    # def _validate_compute_parameters(
    #     dipoles: torch.Tensor,
    #     cell: torch.Tensor,
    #     positions: torch.Tensor,
    #     neighbor_indices: torch.Tensor,
    #     neighbor_vectors: torch.Tensor,
    #     smearing: Optional[float],
    # ) -> None:
    #     device = positions.device
    #     dtype = positions.dtype

    #     # check shape, dtype and device of positions
    #     num_atoms = len(positions)
    #     if list(positions.shape) != [len(positions), 3]:
    #         raise ValueError(
    #             "`positions` must be a tensor with shape [n_atoms, 3], got tensor "
    #             f"with shape {list(positions.shape)}"
    #         )

    #     # check shape, dtype and device of cell
    #     if list(cell.shape) != [3, 3]:
    #         raise ValueError(
    #             "`cell` must be a tensor with shape [3, 3], got tensor with shape "
    #             f"{list(cell.shape)}"
    #         )

    #     if cell.dtype != dtype:
    #         raise ValueError(
    #             f"type of `cell` ({cell.dtype}) must be same as `positions` ({dtype})"
    #         )

    #     if cell.device != device:
    #         raise ValueError(
    #             f"device of `cell` ({cell.device}) must be same as `positions` "
    #             f"({device})"
    #         )

    #     if smearing is not None and torch.equal(
    #         cell.det(), torch.tensor(0.0, dtype=cell.dtype, device=cell.device)
    #     ):
    #         raise ValueError(
    #             "provided `cell` has a determinant of 0 and therefore is not valid for "
    #             "periodic calculation"
    #         )

    #     # check shape, dtype & device of `charges`
    #     if charges.dim() != 2:
    #         raise ValueError(
    #             "`charges` must be a 2-dimensional tensor, got "
    #             f"tensor with {charges.dim()} dimension(s) and shape "
    #             f"{list(charges.shape)}"
    #         )

    #     if list(charges.shape) != [num_atoms, charges.shape[1]]:
    #         raise ValueError(
    #             "`charges` must be a tensor with shape [n_atoms, n_channels], with "
    #             "`n_atoms` being the same as the variable `positions`. Got tensor with "
    #             f"shape {list(charges.shape)} where positions contains "
    #             f"{len(positions)} atoms"
    #         )

    #     if charges.dtype != dtype:
    #         raise ValueError(
    #             f"type of `charges` ({charges.dtype}) must be same as `positions` "
    #             f"({dtype})"
    #         )

    #     if charges.device != device:
    #         raise ValueError(
    #             f"device of `charges` ({charges.device}) must be same as `positions` "
    #             f"({device})"
    #         )

    #     # check shape, dtype & device of `neighbor_indices` and `neighbor_distances`
    #     if neighbor_indices.shape[1] != 2:
    #         raise ValueError(
    #             "neighbor_indices is expected to have shape [num_neighbors, 2]"
    #             f", but got {list(neighbor_indices.shape)} for one "
    #             "structure"
    #         )

    #     if neighbor_indices.device != device:
    #         raise ValueError(
    #             f"device of `neighbor_indices` ({neighbor_indices.device}) must be "
    #             f"same as `positions` ({device})"
    #         )

    #     if neighbor_distances.shape != neighbor_indices[:, 0].shape:
    #         raise ValueError(
    #             "`neighbor_indices` and `neighbor_distances` need to have shapes "
    #             "[num_neighbors, 2] and [num_neighbors], but got "
    #             f"{list(neighbor_indices.shape)} and {list(neighbor_distances.shape)}"
    #         )

    #     if neighbor_distances.device != device:
    #         raise ValueError(
    #             f"device of `neighbor_distances` ({neighbor_distances.device}) must be "
    #             f"same as `positions` ({device})"
    #         )
